### ISSUE TITLE
#Invalid_link_generation

### ISSUE THREAD

**Issue by arindamss007** [jaykali/maskphish#55] opened 2021-07-22 09:27 UTC
When trying to hide a phishing link then its generating a invalid phishing link and my operating system is : Ubuntu . Please fix the problem.

**Comment by jaykali** [comment] 2021-07-22 12:02
Please provide a screenshot of the error.

**Comment by arindamss007** [comment] 2021-07-22 12:26
Thank you for responding to my issue report. I'll give you some pictures
then you can see it's not generating a proper link !

**Comment by mayankyadav778** [comment] 2021-07-25 18:40
Getting the same error
3 days ago
When trying to hide a phishing link then its generating a invalid phishing link and my operating system is : kali linux 2021

**Comment by jaykali** [comment] 2021-07-26 05:56
You still didn't provide the screenshot.

**Comment by arindamss007** [comment] 2021-07-26 05:59
Yes I provide you screen shot in mail please check ✅

**Comment by jaykali** [comment] 2021-07-26 06:28
in which mail?

**Comment by arindamss007** [comment] 2021-07-26 07:05
8436388684 👈 wp number send me hi. I'll give you the screen shot 👏

**Comment by mayankyadav778** [comment] 2021-07-26 08:03
![IMG_20210726_133235](https://user-images.githubusercontent.com/87947021/126954552-52952808-dc92-4b6f-807f-1c523a33d15e.jpg)

**Comment by mayankyadav778** [comment] 2021-07-26 08:04
The link generated by the maskphish doesn't work ,i have checked the ngrok link it works fine.

**Comment by jaykali** [comment] 2021-07-26 11:44
Will fix it. Give us some time.

**Comment by iamdamni** [comment] 2021-07-26 15:33
![image](https://user-images.githubusercontent.com/87988808/127016740-3b08818d-c287-4188-8768-4fd882eb37d8.png)

same error

**Comment by iamdamni** [comment] 2021-07-26 15:34
Please let me know, if something is wrong........

**Comment by jaykali** [comment] 2021-07-26 15:35
> ![IMG_20210726_133235](https://user-images.githubusercontent.com/87947021/126954552-52952808-dc92-4b6f-807f-1c523a33d15e.jpg)

@mayankyadav778 and @arindamss007 Check this screenshot. Here we did exactly as you. But check the result. Did you guys have working internet connection? Or firewall is blocking something.

**Comment by jaykali** [comment] 2021-07-26 15:37
> Please let me know, if something is wrong........

In our system everything is working perfectly. Can you please check a command for me on your system?

**Comment by iamdamni** [comment] 2021-07-26 15:40
![image](https://user-images.githubusercontent.com/87988808/127017673-011be8e9-4e89-49bd-9604-a07784032536.png)

I don't know why iam getting this, I tried as you did above. But its not working for me

**Comment by jaykali** [comment] 2021-07-26 15:40
@iamdamni @arindamss007 @mayankyadav778 Can you guys please run the following command on your terminal and send the screenshot:

`curl -s https://is.gd/create.php\?format\=simple\&url\=https://www.google.com`

**Comment by iamdamni** [comment] 2021-07-26 15:41
![image](https://user-images.githubusercontent.com/87988808/127018029-21620c2c-e512-4f84-b22e-81744f30b66a.png)

Here is the result

**Comment by jaykali** [comment] 2021-07-26 15:44
> ![image](https://user-images.githubusercontent.com/87988808/127018029-21620c2c-e512-4f84-b22e-81744f30b66a.png)
> 
> Here is the result

@Hax4us Bro curl is not working in their system. Any possible reason? @arindamss007 @mayankyadav778 @iamdamni You guys all facing the same problem. Let me think about it.

**Comment by iamdamni** [comment] 2021-07-26 15:48
@jaykali I just now installed curl.....even then its not generating proper link

**Comment by arindamss007** [comment] 2021-07-26 16:20
After running "curl -s
https://is.gd/create.php\?format\=simple\&url\=https://www.google.com" the
result is the same on my os "Ubuntu". I tried many ways according to the
tool but it's not working yet as proof is given below !

**Comment by mayankyadav778** [comment] 2021-07-26 18:13
> ![maskphish](https://user-images.githubusercontent.com/62602243/127017072-d3f1c5fb-d019-4c32-b116-2f2db9e49e1f.png)
> 
> > ![IMG_20210726_133235](https://user-images.githubusercontent.com/87947021/126954552-52952808-dc92-4b6f-807f-1c523a33d15e.jpg)
> 
> @mayankyadav778 and @arindamss007 Check this screenshot. Here we did exactly as you. But check the result. Did you guys have working internet connection? Or firewall is blocking something.

The ngrok link works perfectly.

**Comment by iamdamni** [comment] 2021-07-26 19:03
![image](https://user-images.githubusercontent.com/87988808/127044237-a0d182d6-be39-4183-af6c-19dda441f361.png)

Why this is happening?
Please let me am i doing it wrong?

**Comment by iamdamni** [comment] 2021-07-26 19:05
Only while doing ngrok, its happening like this, rest everything works

**Comment by iamdamni** [comment] 2021-07-26 19:05
Please help me to solve this issue

**Comment by mayankyadav778** [comment] 2021-07-26 20:02
> @iamdamni @arindamss007 @mayankyadav778 Can you guys please run the following command on your terminal and send the screenshot:
> 
> `curl -s https://is.gd/create.php\?format\=simple\&url\=https://www.google.com`

![IMG_20210727_013210](https://user-images.githubusercontent.com/87947021/127051440-aabc6b0d-80a4-48f1-adb1-8b51aaf6e4b4.jpg)

**Comment by jaykali** [comment] 2021-07-27 05:11
> ![image](https://user-images.githubusercontent.com/87988808/127044237-a0d182d6-be39-4183-af6c-19dda441f361.png)
> 
> Why this is happening?
> Please let me am i doing it wrong?

In this case you are using older version of Maskphish. Not everyone, but you.

**Comment by jaykali** [comment] 2021-07-27 05:12
> @jaykali I just now installed curl.....even then its not generating proper link

curl was already installed on your system. But one thing I can't understand why curl -s commands not working in some systems.

**Comment by Hax4us** [comment] 2021-07-27 12:35
> ![image](https://user-images.githubusercontent.com/87988808/127018029-21620c2c-e512-4f84-b22e-81744f30b66a.png)
> 
> Here is the result
ok then let's on the verbose mode to see what's happening
`curl -s -v https://is.gd/create.php\?format\=simple\&url\=https://www.google.com`

**Comment by iamdamni** [comment] 2021-07-27 15:51
![image](https://user-images.githubusercontent.com/87988808/127185966-cbda54e1-6a94-4ea2-a291-7c2385a5afa9.png)

I cant even understand why this is happening, please help!

**Comment by Hax4us** [comment] 2021-07-27 15:56
can you ping that site ?
`ping is.gd`

**Comment by iamdamni** [comment] 2021-07-27 15:59
![image](https://user-images.githubusercontent.com/87988808/127187162-12cef431-94c9-4575-a09e-a2bdc151c482.png)

Iam not getting response

**Comment by Hax4us** [comment] 2021-07-27 16:06
can you ping google ?

**Comment by iamdamni** [comment] 2021-07-27 16:12
![image](https://user-images.githubusercontent.com/87988808/127189344-4c23c20f-b8c3-49d5-b2de-97aae2b99345.png)

Im getting response

**Comment by Hax4us** [comment] 2021-07-27 16:19
try `curl --ipv6  -s -v https://is.gd/create.php\?format\=simple\&url\=https://www.google.com`

**Comment by iamdamni** [comment] 2021-07-27 16:21
![image](https://user-images.githubusercontent.com/87988808/127190743-914b8f4f-e5c4-40d0-8afc-c3b744c6c51f.png)

Here is the result

**Comment by iamdamni** [comment] 2021-07-27 16:27
is.gd is not working? Am i right?

**Comment by jaykali** [comment] 2021-07-27 16:48
![is gd](https://user-images.githubusercontent.com/62602243/127194868-e10a8464-3ea2-4be8-b514-d1fbbf5db96b.png)

**Comment by iamdamni** [comment] 2021-07-27 16:49
What's wrong with me then?
I installed kali again today

**Comment by iamdamni** [comment] 2021-07-27 16:49
Still not working

**Comment by iamdamni** [comment] 2021-07-27 16:49
I think so 443 port is blocking, do u have any solution for it?

**Comment by iamdamni** [comment] 2021-07-27 17:00
Guys i think so, i am having issues with my router
I tried the same thing in aws console

I got exact result, the link works perfectly in aws

Here is the solution i got when i run maskphish in aws

![image](https://user-images.githubusercontent.com/87988808/127196519-62ccb2cd-a2bb-487a-93ff-814a237bef38.png)

Thank you so much anyways.

**Comment by jaykali** [comment] 2021-07-27 17:04
Yap. This tool is not so much complicated to getting errors. Glad that you solved it. I always know there are some issue with connection. CLOSING

**Closed by jaykali** 2021-07-27 17:04 UTC

**Comment by mayankyadav778** [comment] 2021-07-27 18:32
> Guys i think so, i am having issues with my router
> I tried the same thing in aws console
> 
> I got exact result, the link works perfectly in aws
> 
> Here is the solution i got when i run maskphish in aws
> 
> ![image](https://user-images.githubusercontent.com/87988808/127196519-62ccb2cd-a2bb-487a-93ff-814a237bef38.png)
> 
> Thank you so much anyways.

Can you explain how you fixed it?

**Comment by mayankyadav778** [comment] 2021-07-27 19:21
![IMG_20210728_005107](https://user-images.githubusercontent.com/87947021/127215039-9cab9cd3-4c95-48b2-97b1-01d1b084e6bf.jpg)
Is this the cause of problem?

**Comment by jaykali** [comment] 2021-07-28 01:55
Actually it is blocked by your ISP. I am also from India. Here is a screenshot without VPN.
![is gd](https://user-images.githubusercontent.com/62602243/127251260-36996ee5-bba5-45c9-858d-8984fa8ffb60.png)

**Comment by mayankyadav778** [comment] 2021-07-28 07:24
> Actually it is blocked by your ISP. I am also from India. Here is a screenshot without VPN.
> ![is gd](https://user-images.githubusercontent.com/62602243/127251260-36996ee5-bba5-45c9-858d-8984fa8ffb60.png)

What should i do now?

**Comment by mayankyadav778** [comment] 2021-07-28 07:46
> Actually it is blocked by your ISP. I am also from India. Here is a screenshot without VPN.
> ![is gd](https://user-images.githubusercontent.com/62602243/127251260-36996ee5-bba5-45c9-858d-8984fa8ffb60.png)

I can access it from my phone in same network.it just don't open in my laptop

**Comment by jaykali** [comment] 2021-07-28 12:07
> > Actually it is blocked by your ISP. I am also from India. Here is a screenshot without VPN.
> > ![is gd](https://user-images.githubusercontent.com/62602243/127251260-36996ee5-bba5-45c9-858d-8984fa8ffb60.png)
> 
> I can access it from my phone in same network.it just don't open in my laptop



    Actually it is blocked by your ISP. I am also from India. Here is a screenshot without VPN.
    is gd

I can access it from my phone in same network.it just don't open in my laptop
That means there are some issue with your laptop. Please check firewall settings. Are you using Android phone? Then you can try using maskphish from Termux.
